-- Fresh local CampusHub schema. Legacy column meanings are retained without display widths or ZEROFILL.
CREATE TABLE tb_blog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    shop_id BIGINT NOT NULL COMMENT '商户id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    title VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
    images VARCHAR(2048) NOT NULL COMMENT '探店照片，多张以逗号分隔',
    content VARCHAR(2048) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '探店文字描述',
    liked INT UNSIGNED NULL DEFAULT 0 COMMENT '点赞数量',
    comments INT UNSIGNED NULL DEFAULT NULL COMMENT '评论数量',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_blog_comments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    blog_id BIGINT UNSIGNED NOT NULL COMMENT '探店id',
    parent_id BIGINT UNSIGNED NOT NULL COMMENT '关联的1级评论id，一级评论为0',
    answer_id BIGINT UNSIGNED NOT NULL COMMENT '回复的评论id',
    content VARCHAR(255) NOT NULL COMMENT '回复内容',
    liked INT UNSIGNED NULL DEFAULT NULL COMMENT '点赞数',
    status TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '状态：0正常，1被举报，2禁止查看',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_follow (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    follow_user_id BIGINT UNSIGNED NOT NULL COMMENT '被关注用户id',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_seckill_voucher (
    voucher_id BIGINT UNSIGNED NOT NULL COMMENT '关联优惠券id',
    stock INT NOT NULL COMMENT '库存',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    begin_time TIMESTAMP NULL DEFAULT NULL COMMENT '生效时间；未配置时为空',
    end_time TIMESTAMP NULL DEFAULT NULL COMMENT '失效时间；未配置时为空',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (voucher_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci
  COMMENT='秒杀优惠券表，与优惠券是一对一关系';

CREATE TABLE tb_shop (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    name VARCHAR(128) NOT NULL COMMENT '商铺名称',
    type_id BIGINT UNSIGNED NOT NULL COMMENT '类型id',
    images VARCHAR(1024) NOT NULL COMMENT '商铺图片，多个图片以逗号分隔',
    area VARCHAR(128) NULL DEFAULT NULL COMMENT '商圈',
    address VARCHAR(255) NOT NULL COMMENT '地址',
    x DOUBLE UNSIGNED NOT NULL COMMENT '经度',
    y DOUBLE UNSIGNED NOT NULL COMMENT '纬度',
    avg_price BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '均价，整数',
    sold INT UNSIGNED NOT NULL COMMENT '销量',
    comments INT UNSIGNED NOT NULL COMMENT '评论数量',
    score INT UNSIGNED NOT NULL COMMENT '评分，1至5分乘10保存',
    open_hours VARCHAR(32) NULL DEFAULT NULL COMMENT '营业时间',
    create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    INDEX foreign_key_type (type_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_shop_type (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    name VARCHAR(32) NULL DEFAULT NULL COMMENT '类型名称',
    icon VARCHAR(255) NULL DEFAULT NULL COMMENT '图标',
    sort INT UNSIGNED NULL DEFAULT NULL COMMENT '顺序',
    create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_sign (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    year YEAR NOT NULL COMMENT '签到年份',
    month TINYINT NOT NULL COMMENT '签到月份',
    date DATE NOT NULL COMMENT '签到日期',
    is_backup TINYINT UNSIGNED NULL DEFAULT NULL COMMENT '是否补签',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_user (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    phone VARCHAR(11) NOT NULL COMMENT '手机号码',
    password VARCHAR(128) NULL DEFAULT '' COMMENT '加密密码',
    nick_name VARCHAR(32) NULL DEFAULT '' COMMENT '昵称',
    icon VARCHAR(255) NULL DEFAULT '' COMMENT '头像',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE INDEX uniqe_key_phone (phone)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_user_info (
    user_id BIGINT UNSIGNED NOT NULL COMMENT '主键，用户id',
    city VARCHAR(64) NULL DEFAULT '' COMMENT '城市名称',
    introduce VARCHAR(128) NULL DEFAULT NULL COMMENT '个人介绍',
    fans INT UNSIGNED NULL DEFAULT 0 COMMENT '粉丝数量',
    followee INT UNSIGNED NULL DEFAULT 0 COMMENT '关注人数',
    gender TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '性别：0男，1女',
    birthday DATE NULL DEFAULT NULL COMMENT '生日',
    credits INT UNSIGNED NULL DEFAULT 0 COMMENT '积分',
    level TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '会员级别',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_voucher (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    shop_id BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '商铺id',
    title VARCHAR(255) NOT NULL COMMENT '代金券标题',
    sub_title VARCHAR(255) NULL DEFAULT NULL COMMENT '副标题',
    rules VARCHAR(1024) NULL DEFAULT NULL COMMENT '使用规则',
    pay_value BIGINT UNSIGNED NOT NULL COMMENT '支付金额，单位分',
    actual_value BIGINT NOT NULL COMMENT '抵扣金额，单位分',
    type TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0普通券，1秒杀券',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1上架，2下架，3过期',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE tb_voucher_order (
    id BIGINT NOT NULL COMMENT '主键',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '下单用户id',
    voucher_id BIGINT UNSIGNED NOT NULL COMMENT '优惠券id',
    pay_type TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '支付方式',
    status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '订单状态',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
    pay_time TIMESTAMP NULL DEFAULT NULL COMMENT '支付时间',
    use_time TIMESTAMP NULL DEFAULT NULL COMMENT '核销时间',
    refund_time TIMESTAMP NULL DEFAULT NULL COMMENT '退款时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
