-- Minimal synthetic schema for an entirely test-owned MySQL instance; no legacy user data.
CREATE TABLE tb_user(id BIGINT UNSIGNED PRIMARY KEY, icon VARCHAR(255) DEFAULT '') ENGINE=InnoDB;
CREATE TABLE tb_shop(id BIGINT UNSIGNED PRIMARY KEY,type_id BIGINT UNSIGNED NOT NULL) ENGINE=InnoDB;
CREATE TABLE tb_follow(id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL,follow_user_id BIGINT NOT NULL) ENGINE=InnoDB;
CREATE TABLE tb_voucher(
 id BIGINT UNSIGNED PRIMARY KEY,shop_id BIGINT UNSIGNED NOT NULL,title VARCHAR(255),sub_title VARCHAR(255),
 rules VARCHAR(1024),pay_value BIGINT,actual_value BIGINT,type TINYINT,status TINYINT,
 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE tb_seckill_voucher(
 voucher_id BIGINT UNSIGNED PRIMARY KEY,stock INT NOT NULL,begin_time TIMESTAMP NOT NULL,end_time TIMESTAMP NOT NULL,
 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE tb_voucher_order(
 id BIGINT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,voucher_id BIGINT UNSIGNED NOT NULL,
 pay_type TINYINT UNSIGNED NOT NULL DEFAULT 1,status TINYINT UNSIGNED NOT NULL DEFAULT 1,
 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,pay_time TIMESTAMP NULL DEFAULT NULL,
 use_time TIMESTAMP NULL DEFAULT NULL,refund_time TIMESTAMP NULL DEFAULT NULL,
 update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
